quarkus.ironjacamar.ra.kind=ibm-mq
quarkus.ironjacamar.ra.config.host-name=${ibm-mq.host-name:localhost}
quarkus.ironjacamar.ra.config.port=${ibm-mq.port:1414}
quarkus.ironjacamar.ra.config.channel=${ibm-mq.channel:DEV.APP.SVRCONN}
quarkus.ironjacamar.ra.config.queue-manager=${ibm-mq.queue-manager:QM1}
quarkus.ironjacamar.ra.config.username=${ibm-mq.app-user:app}
quarkus.ironjacamar.ra.config.password=${ibm-mq.app-password:app}

# MDBAlternaitve.java で使用しているキー "foo" を定義する。
quarkus.ironjacamar.activation-spec.foo.config.destination=DEV.QUEUE.2
quarkus.ironjacamar.activation-spec.foo.config.destination-type=jakarta.jms.Queue

# 動く場合もあるが原因不明のTCP接続エラーが出る場合があるのでテスト用のMQコンテナは無効にしておく。
quarkus.ibm-mq.devservices.enabled=false
