# IBM MQの接続情報
app.mq.host-name=${ibm-mq.host-name:localhost}
app.mq.port=${ibm-mq.port:1414}
app.mq.channel=${ibm-mq.channel:DEV.APP.SVRCONN}
app.mq.queue-manager=${ibm-mq.queue-manager:QM1}
app.mq.user=${ibm-mq.app-user:app}
app.mq.password=${ibm-mq.app-password:app}

# 受信用の設定（前回作成したもの）
app.jms.receive.concurrency=2
app.jms.receive.queue=DEV.QUEUE.2
#app.jms.receive.selector=application_name = '厚板製造可否判定'

# RESTクライアント "test-rest-client" の呼び出し先
quarkus.rest-client.test-rest-client.url=http://localhost:8080

# RESTクライアントのデバッグログ
# https://ja.quarkus.io/version/3.20/guides/rest-client#logging-traffic
quarkus.rest-client.logging.scope=all
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
